
#ifndef UNITS_H
#define UNITS_H

#include <stdint.h>

typedef enum {
   UNITS_TYPE_INFANTRY,
   UNITS_TYPE_H_INFANTRY,
   UNITS_TYPE_MEDIC,
   UNITS_TYPE_TANK,
   UNITS_TYPE_SCOUT,
   UNITS_TYPE_APC,
   UNITS_TYPE_SPA,
   UNITS_TYPE_AAA,
   UNITS_TYPE_SPAR,
   UNITS_TYPE_FIGHTER,
   UNITS_TYPE_BOMBER,
   UNITS_TYPE_TRANS_HELI,
   UNITS_TYPE_BATTLESHIP,
   UNITS_TYPE_SUBMARINE,
   UNITS_TYPE_LANDING_CRAFT,
   UNITS_TYPE_TURRET_ANTI_LAND,
   UNITS_TYPE_TURRET_ANTI_AIR,
   UNITS_TYPE_TURRET_ANTI_SEA,
   UNITS_TYPE_OBSTACLE
} UNITS_TYPE;

typedef enum {
   UNITS_FACING_UP,
   UNITS_FACING_DOWN,
   UNITS_FACING_RIGHT,
   UNITS_FACING_LEFT,
} UNITS_FACING;

struct units_unit {
   uint32_t type;
   uint32_t team;
   struct isomap_tile* tile;
   UNITS_FACING facing;
};

#endif /* UNITS_H */
